config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :users

  validates :gender, presence: true
  validates :describtion, presence: true
  validates :price, presence: true
  validates :category, presence: true
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @products = Product.all
    if params[:query].present?
      @products = Product.where(category: params[:query])
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(products_params)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])

  end

#   def update
#     @product = Product.find(params[:id])
#     @product.update(product_params)
#   end

#   private

#   def product_params
#     params.required(:product).permit(:gender, :describtion, :price, :category, :photo)
#   end

#   def set_product
#     @product = Product.find(params[:id])
#   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>X-Renting - Crossfit Equimpent Renting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>

  </head>

  <body>
  <div class="page-container">
        <%= render "shared/navbar" %>
        <%= render 'shared/flashes' %>
        <main id="main-content">
          <%= yield %>
        </main>
        <%= render "shared/footer" %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="text-center">
  <h1 class="maintext">X-CREW</h1>
  <p class="slogan">Sell & Buy your next X-FIT Equipment & Apparel</p>
</div>

<% if user_signed_in? %>
<% end %>

<div class="container carousel">
  <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="10000">
        <img src="https://img4.goodfon.com/wallpaper/nbig/c/9b/female-fitness-rope-workout.jpg" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item" data-bs-interval="2000">
        <img src="https://selections.rockefeller.edu/wp-content/uploads/2016/07/Crossfit.jpg" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://www.proclub.com/src/assets/images/FitnessPage/subservices/faq/FITNESSANDSPORTS_H_CROSSFIT_FAQ_4K_01092019.jpg" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

app/views/products/index.html.erb
<h1 class="text-center">Buy me!</h1>
    <div class="album py-2 bg-light">
      <div class="container">
        <div class="row product-index">
        <% @products.each do |product| %>
          <div class="col-3">
            <div class="card-product text-center">
              <% if product.photo.attached? %>
                <%= cl_image_tag product.photo.key, height: 120, class:"index-pictures" %>
                <% else %>
                <%= image_tag "#", height: 120, class:"index-pictures"%>
              <%end %>
              <div class="card-body">
                <h4 class="card-title"><%= product.category %></h4>
                <h6 class="card-title"><%= product.gender %></h6>

                <p class="card-text"><%= product.price.to_i %>€</p>
                <a href="<%=product_path(product)%>" class="btn btn-primary">Buy it!</a>
              </div>
            </div>
          </div>
        <%end%>
      </div>
    </div>

app/views/products/new.html.erb
<div class="expand-lg">
  <div class="text-center">
    <div class="container-fluid">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <h3 class="maintext">Sell your X-Crew Product🏋️</h3>
          <%= simple_form_for @product do |f| %>
            <%= f.input :gender %>
            <select class="form-select" aria-label="Default select example">
  <option selected>Choice of Your Item Type</option>
  <option value="1">Men</option>
  <option value="2">Women</option>
  <option value="3">Accessories</option>
</select>
            <%= f.input :describtion %>
            <%= f.input :price %>
            <%= f.input :category %>
            <%= f.input :photo, as: :file%>
            <%= f.submit class: 'btn btn-outline-dark' %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
  <div class="d-flex justify-content-between">
 <div class="surfboard-detail">
 <% if @surfboard.photo.attached? %>
 <%= cl_image_tag @surfboard.photo.key, height: 300, width: 400, crop: :fill %>
 <%end %>
  <h1><%= @surfboard.city %></h1>
  <h2><%= @surfboard.price_day %></h2>
  <h2><%= @surfboard.brand %></h2>
  <h2><%= @surfboard.detail %></h2>
</div>
<%= simple_form_for [@surfboard, @booking] do |f| %>
  <%= f.input :start_day, as: :date, html: true %>
  <%= f.input :end_day, as: :date, html: true %>
  <%= f.submit "Book"  %>
<% end %>
<form class="row g-3 needs-validation" novalidate>
  <div class="col-md-4">
    <label for="validationCustom01" class="form-label">First name</label>
    <input type="text" class="form-control" id="validationCustom01" value="Mark" required>
    <div class="valid-feedback">
      Looks good!
    </div>
  </div>
  <div class="col-md-4">
    <label for="validationCustom02" class="form-label">Last name</label>
    <input type="text" class="form-control" id="validationCustom02" value="Otto" required>
    <div class="valid-feedback">
      Looks good!
    </div>
  </div>
  <div class="col-md-4">
    <label for="validationCustomUsername" class="form-label">E-Mail</label>
    <div class="input-group has-validation">
      <input type="text" class="form-control" id="validationCustomUsername" aria-describedby="inputGroupPrepend" required>
      <div class="invalid-feedback">
        Please choose a E-Mail.
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <label for="validationCustom04" class="form-label">Phone Number</label>
    <div class="input-group has-validation">
      <input type="text" class="form-control" id="validationCustomUsername" aria-describedby="inputGroupPrepend" required>
      <div class="invalid-feedback">
      Please select a valid Phone Number.
    </div>
  </div>
  <div class="col-12">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
      <label class="form-check-label" for="invalidCheck">
        Agree to terms and conditions
      </label>
      <div class="invalid-feedback">
        You must agree before submitting.
      </div>
    </div>
  </div>
  <div class="col-12">
    <button class="btn btn-primary" type="submit">Submit form</button>
  </div>
  </div>
</form>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li><a href="#">Web design</a></li>
                            <li><a href="#">Development</a></li>
                            <li><a href="#">Hosting</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>X-Renting by Fashionable</h3>
                        <p>This homepage is a project with the purpose of showing a portfolio of the work of Giuseppe Trovato during the coding bootcamp at Le Wagon.</p>
                    </div>
                    <div class="col item social"><a href="#">
                      <i class="fab fa-github"></i></a><a href="https://github.com/giutrovato" target="_blank">
                      <i class="fab fa-linkedin"></i></a><a href="https://www.linkedin.com/in/giuseppe-trovato-73b0bb109/" target="_blank">
                      <i class="fab fa-facebook"></i></a><a href="#">
                      <i class="fab fa-instagram"></i></a>
                    </div>
                </div>
                <p class="copyright">Giuseppe Trovato © 2022</p>
            </div>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="text-center">
    <div class="container">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFi5nGjHQUqaq8WV9dFmXqRPaZLkZuHVL3vkZM_cdgOPPvQbVhePJLfyu43MQ4Q92kaeA&usqp=CAU" alt="" width="60" height="60" class="text-center">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    </div>
  </div>
</nav>

  <nav class="navbar navbar-expand-lg">
    <div class="text-center">
      <div class="container">
        <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
          <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
              <% if user_signed_in? %>
                <li class="nav-item active">
                  <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Menswear", products_path(query: "Menswear"), class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Womenswear", products_path(query: "Womenswear"), class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Accessories", products_path(query: "Accessories"), class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "SELL IT!", new_product_path, class: "nav-link" %>
                </li>
                <a class="fa fa-shopping-cart" href="#"></a>
                <li class="nav-item dropdown">
                  <%= image_tag "https://poolbeschichtung.ch/wp-content/uploads/2022/04/rafael-philipp-poolbeschichtung-schweiz.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <%= link_to "Bookings", "#", class: "dropdown-item" %>
                    <%= link_to "Messages", "#", class: "dropdown-item" %>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                  </div>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Login", new_user_session_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>